version: "3.8"
services: 
  app:
    container_name: app
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    restart: always
    command: yarn dev
    environment:
      - NODE_ENV=development
      - POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}
      - POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
      # Uncomment the next line if you’re using Windows
      - WATCHPACK_POLLING=true
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: delegated
      - type: volume
        source: node_modules
        target: /app/node_modules
      - type: volume
        source: next
        target: /app/.next
    ports:
      - 3000:3000
    x-develop:
      watch:
        - ./

  database-app:
    container_name: database-app
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - my-db:/var/lib/postgresql/data
# Volume for MySQL data persistence
volumes:
  my-db: ~
  node_modules:
  next:
