import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SpeedInsights } from '@vercel/speed-insights/next';
import Navbar from '@/components/ui/navbar/Navbar';
import getCurrentUser from './actions/getCurrentUser';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />

        <Navbar currentUser={currentUser} />
        <div className="pb-20 pt-28">{children}</div>
        <SpeedInsights />
      </body>
    </html>
  );
}
